
name: code analysis

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  biome:
    name: biome static check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node + PNPM + Install Deps
        uses: ./.github/actions/setup

      - name: Run Biome Static Check
        run: pnpm biome ci .

  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node + PNPM + Install Deps
        uses: ./.github/actions/setup

      - name: Run TypeScript Type Check
        run: pnpm typecheck
        shell: bash
